<?php

namespace AsayDev\LaraTickets;

use Illuminate\Support\ServiceProvider;

/**
 * Class AsayDevTicketsServiceProvider.
 */
class AsayDevLaraTicketsServiceProvider extends ServiceProvider
{


    public function boot()
    {
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'asaydev-lara-tickets');
    }


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
