<?php

namespace AsayDev\LaraTickets;

use AsayDev\LaraTickets\Console\InstallLaraTicketsPackage;
use Illuminate\Support\ServiceProvider;

/**
 * Class AsayDevTicketsServiceProvider.
 */
class AsayDevLaraTicketsServiceProvider extends ServiceProvider
{


    public function boot()
    {
        if ($this->app->runningInConsole()) {
            // publish config file
            $this->commands([
                InstallLaraTicketsPackage::class,
            ]);
        }

        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'asaydev-lara-tickets');
    }


    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub

        $this->mergeConfigFrom(__DIR__.'/../config/laratickets.php', 'laratickets');

    }
}
